### ISSUE TITLE
Finalizing the distance and diversity modules

### ISSUE THREAD

**Issue by FanwangM** [theochem/DiverseSelector#109]
This part remains to be finished for the first official release.

**Comment by FanwangM** [comment]
The following resources might be of help.

- https://vlachosgroup.github.io/AIMSim/implemented_metrics.html
-

**Comment by PaulWAyers** [comment]
@FanwangM is there something I need to do to help this? Any ambiguity about  what remains to be done?

**Comment by FanwangM** [comment]
> @FanwangM is there something I need to do to help this? Any ambiguity about  what remains to be done?

As we planned before, someone in @FarnazH group will help with this part. Can you ask he/she to make a pull request if there are any codes in local machine? Thanks.

**Comment by PaulWAyers** [comment]
I think we should probably make a very clear plan on what is going to be done; I guess that @Ali-Tehrani was the person from Farnaz's group who was involved, but I don't remember. Do you?

**Comment by FanwangM** [comment]
## Dissimilarity/Diversity Measurements

Here is the list that we are going to support for **dissimilarity/diversity**. This will go to [diversity.py](diversity.py)

1. total diversity column, Eq. 4 on page 843 of [J. Chem. Inf. Comput. Sci. 1997, 37, 841-851](https://pubs.acs.org/doi/10.1021/ci9700337) (the first method in this paper)
2. Eq. 9 on page 844 of [J. Chem. Inf. Comput. Sci. 1997, 37, 841-851](https://pubs.acs.org/doi/10.1021/ci9700337) (the second method in this paper)
3. Gini coefficient from [Journal of Computational Chemistry2016,37, 2091–2097](https://onlinelibrary.wiley.com/doi/10.1002/jcc.24423), Eq 12, 13 as well
4. entropy from Eq. 9 on page 4 of [Leguy et al. J Cheminform (2021) 13:76](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00554-8) with implementation at https://github.com/jules-leguy/EvoMol/blob/master/evomol/evaluation_entropy.py
5. log-determinant function from [Sci. Rep. 12: 1124 (2022)](https://www.nature.com/articles/s41598-022-04967-9)
6. Wasserstein distance for property‑based evaluation of diversity. from [Sci. Rep. 12: 1124 (2022)](https://www.nature.com/articles/s41598-022-04967-9) with codes available at https://github.com/tomotomonakanaka/SUBMO
7. Explicit Diversity Index from [J. Chem. Inf. Model. 2006, 46, 5, 1898–1904](https://pubs.acs.org/doi/10.1021/ci060074f)
8.  determinantal point processes as a diversity measure
    - [fast greedy algorithm](https://proceedings.neurips.cc/paper/2018/file/dbbf603ff0e99629dda5d75b6f75f966-Paper.pdf)
    - [review](https://arxiv.org/pdf/1207.6083.pdf)
    - [code](https://dppy.readthedocs.io/en/latest/finite_dpps/exact_sampling.html#finite-dpps-exact-sampling)
    - [two algorithms here](https://proceedings.neurips.cc/paper/2014/file/4462bf0ddbe0d0da40e1e828ebebeb11-Paper.pdf)

## Similarity

Similarity and scaled similarity $\frac{S(i,j)}{SQRT(S(i,i)S(j,j)}$. More in https://github.com/theochem/DiverseSelector/issues/73

## Conversion Between Similarity and Dissimilarity

https://rdrr.io/cran/smacof/man/sim2diss.html. 

## Todo:
[ ] finish un-implemented algorithms/methods
[ ] support p-sum, which has been implemented in `Scikit-Learn`, https://github.com/theochem/DiverseSelector/issues/57
[ ] Fix the problem listed in #67 
[ ] Add more testings

**Comment by FanwangM** [comment]
I have written a short summary for distance/dissimilarity/similarity modules. As I recalled, there will be some undergraduate researchers in @FarnazH group who will take care of this part. If no one is going to do this, I will then take care of it. Can you tell me what you think? Thank you.
@PaulWAyers @FarnazH @Ali-Tehrani

**Comment by FanwangM** [comment]
Suppressed by #121 and #122.
