### ISSUE TITLE
Add support of heapsweep

### ISSUE THREAD

**Issue by FanwangM** [theochem/DiverseSelector#112]
This is inspired by the https://chemfp.readthedocs.io/en/chemfp-4x/chemfp_diversity.html?highlight=%20MaxMin#heapsweep-picker
and the paper is https://doi.org/10.1016/j.tcs.2015.02.033. Not sure if the efforts are worth this implementation.

Also, some picking methods can be interesting to explore in this webpage. 

What do you think of this? @PaulWAyers @FarnazH @alnaba1 @RichRick1 @Ali-Tehrani

**Comment by PaulWAyers** [comment]
I'm not sure it is worth adding. I'd put this as an issue and lean towards example notebooks using other packages with DiverseSelector or to compare with DiverseSelector, rather than rewriting/appropriating the methods.

**Comment by FanwangM** [comment]
This makes sense. Thank you.

**Comment by FanwangM** [comment]
Can you also try to add https://chemfp.readthedocs.io/en/chemfp-4x/chemfp_diversity.html?highlight=%20MaxMin#heapsweep-picker in our algorithm performance profiling when selecting molecules from the dataset? Thank you. @Shania99

**Comment by PaulWAyers** [comment]
From the reading here, it seems that heapsweep is slower than maxmin and usually used only when you want to find all equivalent guesses. It's fine to profile against it, but since it's even slower than maxmin (and that behavior is already known), I'm not sure why to include it.

**Comment by FanwangM** [comment]
We don't have a plan to include this implementation for now. But maybe we can mention it in the manuscript. 

Thanks to your suggestions, we are not going to benchmark it.

**Comment by FanwangM** [comment]
Given the fact we don't have a plan to include this, I am going to close this issue for now.
