### ISSUE TITLE
[Utils] Utils.py has unfinished to-do and lacks testing

### ISSUE THREAD

**Issue by AWBroscius** [theochem/DiverseSelector#131]
The utils.py has a large to-do block [here](https://github.com/theochem/DiverseSelector/blob/polish_distance/DiverseSelector/utils.py#L89) Is implementation of this is still needed?

Also, [mol_loader()](https://github.com/theochem/DiverseSelector/blob/polish_distance/DiverseSelector/utils.py#LL48C16-L48C16) needs tests written for it in [test_util.py](https://github.com/theochem/DiverseSelector/blob/polish_distance/DiverseSelector/test/test_util.py)

**Comment by PaulWAyers** [comment]
I think that @FanwangM may already have code to do this, probably in a different repository for a different project.

**Comment by PaulWAyers** [comment]
I can also imagine outsourcing this to an external package, and just require the user to handle the input. I think it's a good question for @FanwangM

**Comment by PaulWAyers** [comment]
This add-on should be demonstrated with a Jupyter Notebook, and not part of the main package I think.
