### ISSUE TITLE
A few more questions regarding #147

### ISSUE THREAD

**Issue by FanwangM** [theochem/DiverseSelector#152]
Thank you again for your efforts in building the notebook. @marco-2023

I am copying the list of questions as a reminder/placeholder here for reference as I have merged #147.

- [ ]  Would it be more precise to say "Running QC-Selector" instead of "Running Dissimilarity Algorithms" because we have multiple flavors for subset selection;
- [ ]  Do we have any explanations on why we get 8 and 6 data points instead of the queried 12 for "Adapted Optimizable K-Dissimilarity Selection (OptiSim)"?
- [ ]  Can we put all the imports at the top of the jupyter notebook?
- [ ]  For each subplot, can we add a title, x label and y label so that people don't have to scroll up to see what the figure means?
- [ ]  Can you add a few words saying why MaxSum is sensitive to outliers above the figure?
- [ ]  Why Directed Sphere Exclusion is giving 13 molecules instead of 12?
-

**Comment by marco-2023** [comment]
Thanks @FanwangM  for the remainder. I tried answering these points in PR #157
