### ISSUE TITLE
Identify/Choose Methods for Selecting Diverse Samples

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/DiverseSelector#2]

**Comment by PaulWAyers** [comment]
@Ali-Tehrani  suggested using determinantal point processes. There is code (Julia and Python that I found) for doing this
https://github.com/theogf/DeterminantalPointProcesses.jl
https://github.com/guilgautier/DPPy
https://github.com/mbp28/determinantal-point-processes
https://github.com/sverdoot/regularized-dpp

This last code implements this paper https://arxiv.org/pdf/1906.04133.pdf .

Some other papers are:
http://proceedings.mlr.press/v99/derezinski19a/derezinski19a.pdf
https://openreview.net/pdf?id=BkzBwNrlLS

This paper, which @Ali-Tehrani found, suggests that diverse sampling not only improves the performance (speed) but also the accuracy/robustness of kernel methods (based on the abstract, which is all I've read so far)
https://arxiv.org/abs/2002.08616

**Comment by fwmeng88** [comment]
Thanks for sharing! Looks very promising! @PaulWAyers @airi-kawasaki 

Paper on `DPPy` can be found at `tools` subfolder that we shared.

**Comment by fwmeng88** [comment]
A practical example using DPP for diverse subset sampling can be found at [Fast mixing Markov chains for strongly rayleigh measures, DPPs, and constrained sampling](https://proceedings.neurips.cc/paper/2016/file/850af92f8d9903e7a4e0559a98ecc857-Paper.pdf). @PaulWAyers @Ali-Tehrani

**Comment by PaulWAyers** [comment]
The strategy I was proposing for using kd-trees to make maximally diverse samples is not new.
https://pubs-acs-org.libaccess.lib.mcmaster.ca/doi/abs/10.1021/ci980100c

**Comment by PaulWAyers** [comment]
Subsumed by #7
