### ISSUE TITLE
Methods for Assessing the Diversity of a Set (and how optimal it is)

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/DiverseSelector#4]
For example, we could measure how much more diverse a selected sample is than a random sample.

If clusters are similar size, then random-ish samples are a lot better than if clusters are very inhomogenous in size.

**Comment by RichRick1** [comment]
Found [this](https://mcmasteru365-my.sharepoint.com/personal/mengf9_mcmaster_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmengf9%5Fmcmaster%5Fca%2FDocuments%2Fshared%2Fchemical%20diversity%20based%20sampling%20papers%2FDiversity%20selection%20algorithms%2Epdf&parent=%2Fpersonal%2Fmengf9%5Fmcmaster%5Fca%2FDocuments%2Fshared%2Fchemical%20diversity%20based%20sampling%20papers) paper really easy to follow and it describes a couple of algorithm (**clustering and Dissimilarity-Based Compound Selection**) that might be relatively easy to implement at the beginning. Also, _Dissimilarity-Based Compound Selection_ provides a decent metric while quality of the _Clustering_ approach can be used as Gini Index/ Entropy. Here are some screenshots:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/36164007/151202572-bfa8928e-7db9-4b3e-8832-f8b21e33fcec.png">

And for the clustering algorithm:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/36164007/151202810-21d507e6-323d-4a95-9cd3-96256c7a4af3.png">

So, overall steps might be:
1. Build (or let the user input) the dissimilarity matrix as a np.array/sparse array/ .txt file (?). 
2. Use either proposed  _Dissimilarity-Based Compound Selection_  which doesn't require a lot of computation power and/or  resource. Another choice at this stage might be to use clustering algorithm (hierarchical (application can be found in [this paper](https://mcmasteru365-my.sharepoint.com/personal/mengf9_mcmaster_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmengf9%5Fmcmaster%5Fca%2FDocuments%2Fshared%2Fchemical%20diversity%20based%20sampling%20papers%2FA%20systematic%20way%20of%20clustering%20and%20selecting%20a%20representative%20set%20of%20new%20psychoactive%20substances%2Epdf&parent=%2Fpersonal%2Fmengf9%5Fmcmaster%5Fca%2FDocuments%2Fshared%2Fchemical%20diversity%20based%20sampling%20papers)), k-means/ DBSCAN/ etc) and than just select the required amount of samples from each cluster. 
3. Use the Gini Index/ Entropy to decide how diverse dataset is 

Potential problems might be:
1. How to select number of clusters for clustering problem (can be done using elbow method and/or silhouette coefficient)
2. Clustering algorithm in general doesn't work great, so maybe we need to compare the output with a threshold random sampling
3. How to deal with imbalanced datasets 


@fwmeng88 please, let me know what do you think about this

**Comment by PaulWAyers** [comment]
I think these are two great brute-strength methods for generating samples. Selecting the right number of clusters is probably easily left to the user; a default option could be to select the number of clusters to equal the size of the sample desired. A simple revision would be to take `n_members` elements from each of `n_clusters` clusters to generate `n_members*n_clusters` samples, where any deficit (because of a cluster not having enough members) is resolved in some way (random sample or dissimilarity-based selection).

I thinks some of the other methods are more efficient, but for most molecular databases these (very robust; should be extremely reliable, only potential issue is cost) methods should be very reliable.

**Comment by fwmeng88** [comment]
This paper is very interesting. Thanks for proposing the idea. @RichRick1 

**DBCS** can be the very first few examples that we can implement. But we may need to think about its tendency to select outliers, which relates to the problem you mentioned, class imbalance. These two problems are not identical, but closely related.  An alternative to this is the sphere of exclusion algorithm ([J. Chem. Inf. Comput. Sci. 1995, 35, 1, 59–67](https://pubs.acs.org/doi/pdf/10.1021/ci00023a009) and [ACS Chem. Biol. 2011, 6, 3, 208–217](https://pubs.acs.org/doi/10.1021/cb100420r)). 

Another possibility is that we can try clustering together with the Monte Carlo search. Based on @PaulWAyers's comments above, we can try a clustering algorithm that can provide probability information (soft clustering) and then take a few members out of each cluster to form a new sample set. Then we use the Monte Carlo search to improve the diversity.
 @RichRick1

**Comment by PaulWAyers** [comment]
An article I was trying to remember but (finally) found is:
   https://pubs-acs-org.libaccess.lib.mcmaster.ca/doi/10.1021/ci500749q
   https://europepmc.org/article/med/25594586
This basically uses the maximin algorithm (the dissimilarity-based selection) but uses a grid to make it linear scaling. 

The directed sphere evolution method is a sphere-of-exclusion method that seems (slightly) better than the most direct approach. It's implemented in the `chemalot` code (but not in Python)
    https://github.com/chemalot/chemalot

I'm starting to feel like we probably have enough algorithms here, unless there is something really amazing out there. But having:
- brute strength dissimilarity (expensive; prone to select outliers)
- dissimilarity maximization with a grid (not perfectly optimal; less prone to select outliers) 
- directed sphere evolution (cheaper; less prone to outliers)
- clustering+selection

The first papers above suggest that when you have values of the target property, you can sample (even with stratification) within boxes/clusters to ensure diverse samples for the target property, or to select a library that is good for the target property.

This would give us three or four families of methods. With enough work there, the bigger indicator of performance is likely to end up being how good our *metric* is for selecting molecules...which is something that is a never-ending task, where we mostly need to support a wide variety of metrics.

**Comment by PaulWAyers** [comment]
Determinantal point processes seem really cool here; they maximize the volume of the parallelpiped containing the data, and in that sense ensure that the "interpolation regime" is as big as possible.

**Comment by fwmeng88** [comment]
The *brute strength dissimilarity* method has been implemented in https://rdrr.io/cran/caret/man/maxDissim.html and the original paper is [Willett, P. (1999), "Dissimilarity-Based Algorithms for Selecting Structurally Diverse Sets of Compounds," Journal of Computational Biology, 6, 447-457.](https://www.liebertpub.com/doi/10.1089/106652799318382).

**Comment by fwmeng88** [comment]
Using Gini coefficient to measure the chemical diversity is a great idea! @RichRick1 
This paper explains more details, [Journal of Computational Chemistry2016,37, 2091–2097](https://onlinelibrary.wiley.com/doi/10.1002/jcc.24423). @PaulWAyers

**Comment by fwmeng88** [comment]
At this moment, I have seen ways to compute the dataset diversity,

1. total diversity column, Eq. 4 on page 843 of [J. Chem. Inf. Comput. Sci. 1997, 37, 841-851](https://pubs.acs.org/doi/10.1021/ci00021a011) (the first method in this paper)
2. Eq. 9 on page 844 of  [J. Chem. Inf. Comput. Sci. 1997, 37, 841-851](https://pubs.acs.org/doi/10.1021/ci00021a011) (the second method in this paper)
3. Gini coefficient from  [Journal of Computational Chemistry2016,37, 2091–2097](https://onlinelibrary.wiley.com/doi/10.1002/jcc.24423)

I will add more as I read.

**Comment by PaulWAyers** [comment]
The Gini coefficient works primarily for the binary fingerprint I think. Entropy could be made to work for more general options, but is probably easiest from a bit-string or another case where there are a discrete number of states (or a known distribution of numbers) for each element in the molecular descriptor vector. I'm not sure how the Gini coefficient could be used if only a (dis)similarity matrix was available (ditto for the entropy there, though). But that's a case where some sort of determinantal measure could work...

The links Fanwang had above seem wrong; try below instead.
https://pubs-acs-org.libaccess.lib.mcmaster.ca/doi/10.1021/ci9700337
Equations 12 and 13 in this paper are also sensible.

There may be some other good things here too.

**Comment by PaulWAyers** [comment]
- [ ] Similarity and scaled similarity (S(i,j)/SQRT(S(i,i)S(j,j))
- [ ] 5 different methods for computing dissimilarity

One of these five (or not?) should be 2S(i,j) - S(i,i) - S(j,j) where S(i,j) is the similarity. This is the distance via a covariance matrix. 
One can also consider S(i,j)/SQRT(S(i,i)S(j,j)) and compute the distance-squared from that. That's a correlation matrix.

**Comment by PaulWAyers** [comment]
Recommendation: Split issue for similarity/dissimilarity and diversity computation.

**Comment by PaulWAyers** [comment]
Notes on Wasserstein Distance to Uniform Distribution (for @Khaleeh )
[Wasserstein-Dist-to-Uniform-Dist.pdf](https://github.com/theochem/DiverseSelector/files/8336829/Wasserstein-Dist-to-Uniform-Dist.pdf)
[Wasserstein-Dist-to-Uniform-Dist.md](https://github.com/theochem/DiverseSelector/files/8336830/Wasserstein-Dist-to-Uniform-Dist.md)

**Comment by PaulWAyers** [comment]
@FarnazH pointed out that it would be very useful to have a very simple API for evaluating the diversity of a subset.

**Comment by PaulWAyers** [comment]
We should implement determinantal point processes as a diversity measure (using the Grammian if features are given; using the distance matrix or one of its implied quantities otherwise).  There are greedy algorithms for optimizing the determinantal point process, which is a very good selection method.
- [fast greedy algorithm](https://proceedings.neurips.cc/paper/2018/file/dbbf603ff0e99629dda5d75b6f75f966-Paper.pdf)
- [review](https://arxiv.org/pdf/1207.6083.pdf)
- [code](https://dppy.readthedocs.io/en/latest/finite_dpps/exact_sampling.html#finite-dpps-exact-sampling)
- [two algorithms here](https://proceedings.neurips.cc/paper/2014/file/4462bf0ddbe0d0da40e1e828ebebeb11-Paper.pdf)

**Comment by fwmeng88** [comment]
> @FarnazH pointed out that it would be very useful to have a very simple API for evaluating the diversity of a subset.

This is good to have and the original plan was set to fix this soon.

**Comment by PaulWAyers** [comment]
Note we should also support p-sums (not just minimum (p=-infinity) and sum (p=1)) versions for the brute-strength algorithm, so that a balanced representation can be achieved.
