### ISSUE TITLE
Add functionality for "holes" in the dataset

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/DiverseSelector#51]
As pointed out by @FarnazH , it would be good to be able to identify which molecules/samples are in low-density regions (where we have little data) and also to identify regions where there is very little (or no) data.

**Comment by fwmeng88** [comment]
`DBSCAN` is good for outliers and we can print out the outliers. This issue can be an example with the Jupyter notebook.

**Comment by fwmeng88** [comment]
A jupyter notebook would be great.
