### ISSUE TITLE
Quantifying the diversity of selcted subset

### ISSUE THREAD

**Issue by fwmeng88** [theochem/DiverseSelector#56]
We will add the functionality to support measuring the subset diversity.

**Comment by fwmeng88** [comment]
This relates to #4.

**Comment by fwmeng88** [comment]
https://github.com/theochem/DiverseSelector/blob/a77b7f6f0dbd1162d02e057a997343a5be499f6b/DiverseSelector/base.py#L113-L136.

**Comment by RichRick1** [comment]
@fwmeng88 do you want to use the function `total_diversity_volume ` from the `metrics.py` as shown in the demo notebook, or use some other method?

**Comment by fwmeng88** [comment]
We will need to provide people the functionality to select functions that have been implemented, `entropy, explicit_diversity_index, logdet, shannon_entropy, wdud and total_diversity_volume`, #65.

I will build a wrapper function soon and you can finish this functionality once my code is merged. @RichRick1
