### ISSUE TITLE
Add support `p-sums`  for the brute-strength algorithm

### ISSUE THREAD

**Issue by FanwangM** [theochem/DiverseSelector#57]
Not just minimum (p=-infinity) and sum (p=1)) versions, but also we need to support p-sums.
This relates to #4.

**Comment by fwmeng88** [comment]
This might of help, https://github.com/storpipfugl/pykdtree.

**Comment by RichRick1** [comment]
https://scikit-learn.org/stable/modules/metrics.html#metrics

**Comment by FarnazH** [comment]
https://jaquesgrobler.github.io/online-sklearn-build/modules/generated/sklearn.metrics.pairwise.pairwise_distances.html

**Comment by RichRick1** [comment]
Here is a code that run MaxMin selection algorithm using p-norm (aka Minkowski) distance:


```
coords, class_labels, arr_dist = generate_synthetic_data(n_samples=100,
                                                         n_features=2,
                                                         n_clusters=1,
                                                         pairwise_dist=True,
                                                         metric="euclidean",
                                                         random_state=42)

p = 10 ## choose the order of the norm
func_distance = lambda x: pairwise_distances(x, metric='minkowski', p=p)
selector = MaxMin(func_distance)
selected_ids = selector.select(arr=coords, num_selected=15)
```

And the output:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/36164007/170135633-7e32b025-0629-4a1f-b160-170fdb3dd283.png">

We can see that selected molecules are different from the p=2 (Euclidean norm):

<img width="773" alt="image" src="https://user-images.githubusercontent.com/36164007/170135763-19442906-dffa-4f4e-bc2c-a0d214bca800.png">

I guess this has to be shown in the demo notebook, @fwmeng88?
Any other things that need to be implemented for this issue?

**Comment by fwmeng88** [comment]
Yes, you are right. Adding this to the notebook would be a great example. Thanks for your hard work on this. @RichRick1
