### ISSUE TITLE
Keywords list

### ISSUE THREAD

**Issue by fwmeng88** [theochem/DiverseSelector#6]
Using the right keywords may help us identify good pieces of literature. Here is a list of keywords that @PaulWAyers and I have used, 

```md
1. chemical diversity;
2. compound selection;
3. maximum diversity molecule;
```

Please feel free to add new keywords if you think that's helpful. If you are adding, adding the numbering would be helpful and I will constantly update the list here for future reference.

Thank you. @Khaleeh @alnaba1 @JuansaCollins @RichRick1

**Comment by fwmeng88** [comment]
New keywords that I came across today,

```md
4. maximum dissimilarity search;
5. variable selection;
```

**Comment by fwmeng88** [comment]
```md
6. compound acquisition
```

**Comment by PaulWAyers** [comment]
Should we add (some of) these to the repo description?

**Comment by fwmeng88** [comment]
Yes, sure. Once we have a decent shape of the package, I will add these to the repo description to help people to find our package more easily.

**Comment by fwmeng88** [comment]
The repo description has been updated with keywords.
