### ISSUE TITLE
List methods which require distance matrix

### ISSUE THREAD

**Issue by fwmeng88** [theochem/DiverseSelector#62]
We need a list of methods that require a distance matrix as mandatory. Currently, if a distance matrix is not provided, the program in `base.py` (line 96-101) will compute the distance matrix, which is unnecessary when a feature matrix is enough. Therefore, can you help list methods that you are taking care of and show which methods must have a distance matrix as input and which methods require the distance matrix as an optional input? Thank you.

@RichRick1 @alnaba1

**Comment by alnaba1** [comment]
@fwmeng88 The only dissimilarity algorithm that uses distance matrix is `brutestrength`, I ensured the rest don't rely on it so they can be more efficient.

**Comment by fwmeng88** [comment]
We need to change some lines of codes to make it more efficient.
