### ISSUE TITLE
Modularize the metric module

### ISSUE THREAD

**Issue by fwmeng88** [theochem/DiverseSelector#65]
The current version of `metrics.py` has implemented several functions and maybe that's too many for people to memorize. So we will end up with a simpler API. I know you may not able to join the hackathon next week. Can you update the status of this module? @Khaleeh 

1. Which are the functions for computing the distance/similarity?
2. Which are the functions for computing diversity?
3. We will need to conversion function to convert distance/similarity/diversity. (This is a reminder for myself.)

Thank you for the nice work!

**Comment by Khaleeh** [comment]
1. `ComputeDistanceMatrix` `euc_bit` `tanimoto` `bit_tanimoto` `modified_tanimoto`
2. `entropy` `explicit_diversity_index` `logdet` `shannon_entropy` `wdud` `total_diversity_volume`
3. it might be useful to expand upon `distance_to_similarity` to include diversity. I forgot to add the reference in the docstring but its [this paper](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-015-0069-3).

I won't be available for the hackathon but I will respond to any questions/messages when I can (probably after 5 on weekdays)/
