### ISSUE TITLE
Implementing k-d trees based method

### ISSUE THREAD

**Issue by FanwangM** [theochem/DiverseSelector#68]
This method is described in [J. Chem. Inf. Comput. Sci. 1999, 39, 1, 51–58](https://pubs.acs.org/doi/abs/10.1021/ci980100c).

**Comment by PaulWAyers** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html

But I think this wraps C++ code so it is hard to modify.

**Comment by PaulWAyers** [comment]
Did we look at this one: J. Chem. Inf. Comput. Sci. 1999, 39, 1, 51–58

**Comment by FanwangM** [comment]
> Did we look at this one: J. Chem. Inf. Comput. Sci. 1999, 39, 1, 51–58

Yes, we did. This is the paper we first started.
