### ISSUE TITLE
Computing dissimilarity/distance/diversity/similarity of molecules

### ISSUE THREAD

**Issue by FanwangM** [theochem/DiverseSelector#7]
An essential component of our package is to have a submodule to compute the dissimilarity/distance/diversity/similarity where normally we assume `diversity = 1 - similarity`.  

A good summary of this is Table 2 in [Drug Dev. Res.,72(1):74 - 84, 2011](https://onlinelibrary.wiley.com/doi/10.1002/ddr.20404). Given a fact that this is a public repo, I am not going to share the screenshot here. 

The [Tanimoto coefficient](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-015-0069-3) is a classic and gold stand similarity metric for molecular fingerprints and we should support it. But it was found that it favors small molecules when used in molecule subset selection and [a modification](https://www.tandfonline.com/doi/abs/10.1198/004017002317375064) was proposed. My guess is that we should make this the default for molecular fingerprint inputs. 

I will keep adding new things. Any idea will be appreciated. 
@PaulWAyers @JuansaCollins @RichRick1 @Khaleeh @alnaba1

**Comment by PaulWAyers** [comment]
A good review is below. Interesting that the guy who wrote it is now the head of research at Pfizer(!)
[9783527613083.ch12.pdf](https://github.com/theochem/DiverseSelector/files/7955681/9783527613083.ch12.pdf)

**Comment by fwmeng88** [comment]
Some implementation of similarity measurements, https://e3fp.readthedocs.io/en/latest/api/e3fp.fingerprint.metrics.html

**Comment by PaulWAyers** [comment]
Some hints on how to do this can be gleaned from e3fp. 
https://github.com/keiserlab/e3fp/blob/b556110243fb535243cdea8d10875f9e4046bbfa/e3fp/fingerprint/metrics/__init__.py

**Comment by PaulWAyers** [comment]
This is also useful for selecting samples. Key ideas (From #2 ) are
- [ ] determinantal point processes
- [ ] KDtrees to make minimax methods faster.

**Comment by PaulWAyers** [comment]
- [ ] Similarity and scaled similarity (S(i,j)/SQRT(S(i,i)S(j,j))
- [ ] 5 different methods for computing dissimilarity

One of these five (or not?) should be S(i,i) + S(j,j)- 2S(i,j) where S(i,j) is the similarity. This is the distance via a covariance matrix and is important in Gaussian processes.
 
One can also consider S(i,j)/SQRT(S(i,i)S(j,j)) and compute the distance-squared from that. That's a correlation matrix/distance.

**Comment by PaulWAyers** [comment]
Different methods for converting similarities to dissimilarities (and vice versa in some cases)
https://rdrr.io/cran/smacof/man/sim2diss.html

**Comment by PaulWAyers** [comment]
Keepers from this issue:
1. Interconversion between similarities and dissimlarities
2. kdtree (for long term)

**Comment by FanwangM** [comment]
Given the topics have been split into smaller chunks, I will close it for now.
