### ISSUE TITLE
Implementing Gini coefficient in `metric.py`

### ISSUE THREAD

**Issue by fwmeng88** [theochem/DiverseSelector#72]

**Comment by fwmeng88** [comment]
The related paper is [Journal of Computational Chemistry2016,37, 2091–2097](https://onlinelibrary.wiley.com/doi/10.1002/jcc.24423)

This relates to #4.

**Comment by Khaleeh** [comment]
Just as a warning me and @PaulWAyers tried to implement this and concluded that the equation is wrong.

**Comment by PaulWAyers** [comment]
I'll look at it again and figure out the right equation and put it here.

**Comment by PaulWAyers** [comment]
The equation given is correct only for the case where the data is uniformly distributed. Then Eq.(1) in this paper is identical to the second expression on the "alternative expressions" list on [wikipedia](https://en.wikipedia.org/wiki/Gini_coefficient#Alternative_expressions)
- bitstrings
- lists/arrays of descriptors where the data is centered and normalized.

Then, for each molecule, we have a feature vector with `L` features, `f(molecule,i)` where `i`=0,1,2,...`L`.

1. sort the feature vector in increasing order. This is probably just `np.sort(f)` but it should be checked.
2. evaluate Eq. (1) with the sorted vectors. 

I think it is nice to avoid sorting. Then you can use:
sum(i,j) |f(molecule,i)-f(molecule(j)| / (2*L**2 * mean(f(molecule,:))

This is the third equation in the first line of https://en.wikipedia.org/wiki/Gini_coefficient#Definition and it might be a bit slower than the presorted version, but it does save the work (and code complexity) from the sort.
