### ISSUE TITLE
Stratified Sampling

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/DiverseSelector#80]
"Simple" stratified sampling can be mimicked by using the propert(ies) of interest as the feature(s). (So the feature vector is exactly the propert(ies) to be sampled.)

To achieve sampling with respect to target properties *and* diversity with respect to a fingerprint/feature-vector, you need to append the target properties to the feature vector. For each property, specify a "repeat": the more times you repeat the property value the higher its weight. 

One way to do this would be to pass a weight, then set the repeat-value for each property to be `repeat = np.ceil(weight*n_features)` where `n_features` is the number of features (length of the fingerprint). (I use ceiling to ensure that as long as weight > 0.0 at least one instance of the property is used). The final feature vector has the property value(s) appended to it `repeat` times. 

Then we use this set of features.

Add a utility for augmenting the feature array and provide examples to showcase this.

**Comment by fwmeng88** [comment]
**The Cauchy-Schwarz Inequality**
$$\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)$$
